### ISSUE TITLE
Enable template repository

### ISSUE THREAD

**Issue by pgollangi** [abelljs/abell-starter-portfolio#2]
Hi, 

First of all thanks for creating this template. I liked it.

Is it possible to make this repo "template repository" on settings.

When I create a new git repo using this as template repo, I see following error:

```
Could not clone: abelljs/abell-starter-portfolio is not a template repository.
```

**Comment by saurabhdaware** [comment]
Done! Totally missed this. Thanks for pointing out :D

**Comment by pgollangi** [comment]
Thanks @saurabhdaware
